// Mocks generated by Mockito 5.4.2 from annotations
// in todo_app/test/Todo%20Task/data/repositories/todo_app_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/core/platform/network_info.dart' as _i6;
import 'package:todo_app/Todo%20Task/data/datasources/todo_task_local_data_source.dart'
    as _i3;
import 'package:todo_app/Todo%20Task/data/datasources/todo_task_remote_data_source.dart'
    as _i5;
import 'package:todo_app/Todo%20Task/data/models/task_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoTaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoTaskLocalDataSource extends _i1.Mock
    implements _i3.TodoTaskLocalDataSource {
  MockTodoTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskModel> getLastTask(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getLastTask,
          [key],
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #getLastTask,
            [key],
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);
  @override
  _i4.Future<List<_i2.TaskModel>> getAllTasks(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [key],
        ),
        returnValue: _i4.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i4.Future<List<_i2.TaskModel>>);
  @override
  _i4.Future<void> cacheTask(_i2.TaskModel? taskToCache) => (super.noSuchMethod(
        Invocation.method(
          #cacheTask,
          [taskToCache],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> cacheAllTasks(
    String? key,
    List<_i2.TaskModel>? taskModels,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAllTasks,
          [
            key,
            taskModels,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TodoTaskRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoTaskRemoteDataSource extends _i1.Mock
    implements _i5.TodoTaskRemoteDataSource {
  MockTodoTaskRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskModel> setDate(
    int? index,
    String? dateTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDate,
          [
            index,
            dateTime,
          ],
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #setDate,
            [
              index,
              dateTime,
            ],
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);
  @override
  _i4.Future<_i2.TaskModel> markCompletion(int? index) => (super.noSuchMethod(
        Invocation.method(
          #markCompletion,
          [index],
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #markCompletion,
            [index],
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);
  @override
  _i4.Future<_i2.TaskModel> addTask(_i2.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #addTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);
  @override
  _i4.Future<List<_i2.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i4.Future<List<_i2.TaskModel>>);
  @override
  _i4.Future<_i2.TaskModel> getTask(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [index],
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #getTask,
            [index],
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
